substitutions:
  name: Bee Hive Scale
  devicename: beehivescale

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
  - ssid: "D6"
    password: "T1gris!42442"
  - ssid: "guest"
    password: "grundfosguest08"
  - ssid: "Isti iPhone 11"
    password: "1234598765"

logger:

ota:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Budapest

mqtt:
  broker: lon1.blynk.cloud
  port: 1883
  username: "device"
  password: "TMsAngO-svohFyOyc9uwCoM_tuPCqOjS"
  client_id: ""
  keepalive: 45s

sensor:
  - platform: wifi_signal
    name: "wiFi signal sensor - $name"
    id: wifisignal
    update_interval: 10s
    on_value:
      - mqtt.publish:
          topic: "ds/Wifi signal"
          payload: !lambda |-
              return to_string(id(wifisignal).state);
  - platform: hx711
    name: "HX711 Value - $name"
    id: hx711_value
    dout_pin: D1
    clk_pin: D2
    gain: 128
    update_interval: 1s
    unit_of_measurement: kg
    filters:
      - quantile:
          window_size: 10
          send_every: 1
          send_first_at: 1
          quantile: .9
      - calibrate_linear:
          - -129100 -> 0
          - -88000 -> 1
    on_value:
      - mqtt.publish:
          topic: "ds/Hive 1 weight"
          payload: !lambda |- 
            return to_string(id(hx711_value).state);
